In [1]:
from app import PrepareTrainAndTestDS

train_ds, val_ds, features = PrepareTrainAndTestDS("data/full_processed_can_data.csv")

2024-11-06 20:16:39.597919: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-06 20:16:39.601171: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-06 20:16:39.612511: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1730924199.630406  119446 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730924199.635567  119446 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 20:16:39.652249: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

Using 23882873 samples for training and 5970718 for validation


2024-11-06 20:17:07.745273: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


Input: {'arbitration_id': <tf.Tensor: shape=(), dtype=int64, numpy=451>, 'df1': <tf.Tensor: shape=(), dtype=int64, numpy=6>, 'df2': <tf.Tensor: shape=(), dtype=int64, numpy=176>, 'df3': <tf.Tensor: shape=(), dtype=int64, numpy=6>, 'df4': <tf.Tensor: shape=(), dtype=int64, numpy=179>, 'df5': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'df6': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'df7': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'df8': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'time_interval': <tf.Tensor: shape=(), dtype=float64, numpy=8.1062316894e-06>}
Target: tf.Tensor(0, shape=(), dtype=int64)


2024-11-06 20:17:10.455491: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


KeyboardInterrupt: 

In [ ]:
for x, y in train_ds.take(1):
    print("Input:", x)
    print("Target:", y)